apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: empty-dir-and-file-in-root
  title: Empty dir and/or file in the root generate the file and folder correctly
spec:
  owner: mknet3
  type: documentation

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
          ui:autofocus: true
        myCondition:
          title: My condition
          type: boolean    

  steps:
    - id: fetch
      name: Template Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          myCondition: ${{ parameters.myCondition }}
